/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.OrderDetails;
import Model.Drink;
import Model.Employee;
import Model.Orders;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class SalesManagement extends javax.swing.JFrame {

    DefaultTableModel modelD;
    DefaultTableModel modelO;
    DefaultTableModel modelLO;
    DefaultTableModel modelOD;
    DefaultTableModel modelDC;
    ArrayList<Drink> drink = Controller.DrinkControl.listDrink();   // danh sach drink
    ArrayList<Integer> list = new ArrayList<>();
    String username;
    Employee e;
    ArrayList<Orders> oL;                       // Danh sach order dang treo
    Orders od;                                  // order dang treo duoc chon
    int tempPrice;
    int tempPriceP;
    ArrayList<Orders> LOD;                      // List order (day)
    /**
     * Creates new form SalesManagement
     */
    public SalesManagement() {
        initComponents();
        setLocationRelativeTo(null);
//        this.username = "admin";
//        this.e = Controller.EmployeeControl.findByUsername(username);
//        oL = Controller.OrderControl.listOU(username);
        modelD = (DefaultTableModel) jTableDrink.getModel();
        modelO = (DefaultTableModel) jTableOrder.getModel();
        modelLO = (DefaultTableModel) jTableLO.getModel();
        modelOD = (DefaultTableModel) jTableOD.getModel();
        modelOD = (DefaultTableModel) jTableOD.getModel();
        modelDC = (DefaultTableModel) jTableDongCa.getModel();
        showTable();
        showOU();
    }

    public SalesManagement(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.username = username;
        this.e = Controller.EmployeeControl.findByUsername(username);
        oL = Controller.OrderControl.listOU(username);
        modelD = (DefaultTableModel) jTableDrink.getModel();
        modelO = (DefaultTableModel) jTableOrder.getModel();
        modelLO = (DefaultTableModel) jTableLO.getModel();
        modelOD = (DefaultTableModel) jTableOD.getModel();
        modelDC = (DefaultTableModel) jTableDongCa.getModel();
        jLabelID.setText(e.getId());
        jLabelName.setText(e.getName());
        showTable();
        showOU();
        showDongCa();
    }

    public void showTable() {
        for (Drink d : drink) {
            modelD.addRow(new Object[]{
                d.getName(), d.getType(), d.getPrice(), Controller.PromotionControl.getPriceP(d)
            });
        }
    }

    public void showOU() {
        int rowCountLO = modelLO.getRowCount();
        // Xoá từng hàng một
        for (int i = rowCountLO - 1; i >= 0; i--) {
            modelLO.removeRow(i);
        }
        int rowCountOD = modelOD.getRowCount();
        // Xoá từng hàng một
        for (int i = rowCountOD - 1; i >= 0; i--) {
            modelOD.removeRow(i);
        }
        oL = Controller.OrderControl.listOU(username);
        for (Orders o : oL) {
            modelLO.addRow(new Object[]{
                o.getId(), o.getDate(), o.getDate().plusMinutes(10)
            });
        }
    }

    public void showDongCa() {
        int rowCountLO = modelDC.getRowCount();
        // Xoá từng hàng một
        for (int i = rowCountLO - 1; i >= 0; i--) {
            modelDC.removeRow(i);
        }
        int p = 0;
        LOD = Controller.OrderControl.listOrderDay(e);
        for (Orders o : LOD) {
            modelDC.addRow(new Object[]{
                o.getId(), o.getIdEmp(), o.getDate(), Controller.OrderControl.convertStatus(o.getStatus()), Controller.OrderControl.convertMethod(o.getMethodPay()), Controller.OrderControl.getPrice(o)
            });
            p += Controller.OrderControl.getPrice(o);
        }
        jLabelDTC.setText(String.valueOf(p));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDrink = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLO = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableOD = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalPay = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableDongCa = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelDTC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jButton5.setText("Quẹt thẻ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Chuyển khoản");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Tiền mặt");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel11.setText("Chọn phương thức thanh toán");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(95, 95, 95))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(31, 31, 31)
                .addComponent(jButton5)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTableDrink.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên đồ uống", "Loại", "Giá gốc", "Giá KM"
            }
        ));
        jTableDrink.setDragEnabled(true);
        jTableDrink.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTableDrinkMouseDragged(evt);
            }
        });
        jTableDrink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDrinkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDrink);

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên đồ uống", "Số lượng", "Giá gốc", "Giá KM", "Ghi chú"
            }
        ));
        jTableOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableOrderMouseEntered(evt);
            }
        });
        jTableOrder.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTableOrderInputMethodTextChanged(evt);
            }
        });
        jTableOrder.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableOrderPropertyChange(evt);
            }
        });
        jTableOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableOrderKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableOrder);

        jButton1.setText("Lập hoá đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Lập order", jPanel2);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jTableLO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã order", "Thời gian lập", "Thời gian hết hạn"
            }
        ));
        jTableLO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLOMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableLO);

        jTableOD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên đồ uống", "Số lượng", "Ghi chú", "Giá gốc", "Giá KM"
            }
        ));
        jScrollPane4.setViewportView(jTableOD);

        jButton2.setText("Huỷ order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Thanh toán");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tổng tiền");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jLabel1))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalPay))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(67, 67, 67))
        );

        jTabbedPane2.addTab("Order đang treo", jPanel3);

        jTableDongCa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã order", "Mã nhân viên", "Thời gian lập", "Trạng thái", "Phương thức TT", "Tổng bill"
            }
        ));
        jScrollPane5.setViewportView(jTableDongCa);

        jButton4.setText("Đóng ca");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tổng doanh thu ca");

        jLabel5.setText("Mã nhân viên");

        jLabelID.setText("admin");

        jLabelName.setText("admin");

        jLabel8.setText("Tên nhân viên");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(34, 34, 34)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelDTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabelName))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabelID)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelDTC))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(22, 22, 22))
        );

        jTabbedPane2.addTab("Đóng ca", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Orders bill = new Orders();
        bill.setId(Controller.OrderControl.ReturnNextIDO());
        int rowCount = modelO.getRowCount();
        for (int i = 0; i <= rowCount - 1; i++) {
            String idD = Controller.DrinkControl.findByName(jTableOrder.getValueAt(i, 0).toString()).getId();
            int q = Integer.parseInt(jTableOrder.getValueAt(i, 1).toString());
            int p = Integer.parseInt(jTableOrder.getValueAt(i, 3).toString());
            String note = jTableOrder.getValueAt(i, 4).toString();
            OrderDetails e = new OrderDetails(bill.getId(), idD, q, p, note);
            Controller.OrderControl.addOD(e);
        }
        bill.setDate(LocalDateTime.now());
        bill.setIdEmp(e.getId());
        bill.setStatus(1);
        Controller.OrderControl.add(bill);
        this.setVisible(false);
        new OrderBill(modelO, bill).show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTableDrinkMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDrinkMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableDrinkMouseDragged

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTableDrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDrinkMouseClicked
        // TODO add your handling code here:
        boolean b = true;
        for (int i : list) {
            if (i == jTableDrink.getSelectedRow()) {
                b = false;
                break;
            }
        }
        if (b) {
            list.add(jTableDrink.getSelectedRow());
            modelO.addRow(new Object[]{
                jTableDrink.getValueAt(jTableDrink.getSelectedRow(), 0).toString(), "1", jTableDrink.getValueAt(jTableDrink.getSelectedRow(), 2).toString(), jTableDrink.getValueAt(jTableDrink.getSelectedRow(), 3).toString(), ""
            });
        }
    }//GEN-LAST:event_jTableDrinkMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jTableOrderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableOrderKeyPressed
        // TODO add your handling code here:
        int vitri = jTableOrder.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            modelO.setValueAt(tempPrice * Integer.parseInt(jTableOrder.getValueAt(vitri, 1).toString()), vitri, 2);
            modelO.setValueAt(tempPriceP * Integer.parseInt(jTableOrder.getValueAt(vitri, 1).toString()), vitri, 3);
        }
        if (Integer.parseInt(modelO.getValueAt(vitri, 1).toString()) == 0) {
            modelO.removeRow(vitri);
        }
    }//GEN-LAST:event_jTableOrderKeyPressed

    private void jTableOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOrderMouseClicked
        // TODO add your handling code here:
        tempPrice = Integer.parseInt(jTableOrder.getValueAt(jTableOrder.getSelectedRow(), 2).toString());
        tempPriceP = Integer.parseInt(jTableOrder.getValueAt(jTableOrder.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_jTableOrderMouseClicked

    private void jTableOrderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableOrderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableOrderPropertyChange

    private void jTableOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOrderMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableOrderMouseEntered

    private void jTableOrderInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTableOrderInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableOrderInputMethodTextChanged

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jTableLOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLOMouseClicked
        // TODO add your handling code here:
        int rowCount = modelOD.getRowCount();
        // Xoá từng hàng một
        for (int i = rowCount - 1; i >= 0; i--) {
            modelOD.removeRow(i);
        }
        for (Orders o : oL) {
            if (jTableLO.getValueAt(jTableLO.getSelectedRow(), 0).toString().equals(o.getId())) {
                od = o;
                for (OrderDetails oD : Controller.OrderControl.listOD(o.getId())) {
                    Drink d = Controller.DrinkControl.findByID(oD.getIdDrink());
                    modelOD.addRow(new Object[]{
                        d.getName(), oD.getQuantity(), oD.getNote(), d.getPrice() * oD.getQuantity(), oD.getPrice()
                    });
                }
                break;
            }
        }
        totalPay.setText(String.valueOf(Controller.OrderControl.getPrice(od)));
    }//GEN-LAST:event_jTableLOMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (LocalDateTime.now().isAfter(od.getDate().plusMinutes(10))) {
            JOptionPane.showMessageDialog(null, "Order đã hết hạn thanh toán, vui lòng huỷ order!");
        } else {
            jFrame1.setSize(359, 143);
            jFrame1.setLocationRelativeTo(null);
            jFrame1.show();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Controller.OrderControl.pay(od.getId(), 3);
        jFrame1.show(false);
        this.setVisible(false);
        new SalesManagement(username).show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Controller.OrderControl.pay(od.getId(), 2);
        jFrame1.show(false);
        this.setVisible(false);
        new SalesManagement(username).show();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Controller.OrderControl.pay(od.getId(), 1);
        jFrame1.show(false);
        this.setVisible(false);
        new SalesManagement(username).show();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn huỷ order này?") == 0) {
            Controller.OrderControl.setStatusOrder(od.getId(), 3);
            showOU();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDTC;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableDongCa;
    private javax.swing.JTable jTableDrink;
    private javax.swing.JTable jTableLO;
    private javax.swing.JTable jTableOD;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JLabel totalPay;
    // End of variables declaration//GEN-END:variables
}
