/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Employee;
import Model.Ingredient;
import Model.IngredientDetails;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class StorageManegement extends javax.swing.JFrame {

    DefaultTableModel modelList, modelNhap, modelXuat, modelHuy, modelTL, modelLNhap, modelLXuat, modelLHuy, modelLTL;
    Employee e;
    ArrayList<IngredientDetails> listInDetails;
    ArrayList<Ingredient> listIngredient;
    ArrayList<Integer> listX = new ArrayList<>();
    ArrayList<Integer> listH = new ArrayList<>();
    ArrayList<Integer> listTL = new ArrayList<>();

    /**
     * Creates new form StorageManegement
     */
    public StorageManegement() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public StorageManegement(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.e = Controller.EmployeeControl.findByUsername(username);
        this.listIngredient = Controller.IngredientControl.listIngredient();
        modelNhap = (DefaultTableModel) jTableNhap.getModel();
        modelXuat = (DefaultTableModel) jTableXuat.getModel();
        modelHuy = (DefaultTableModel) jTableHuy.getModel();
        modelTL = (DefaultTableModel) jTableTL.getModel();
        modelList = (DefaultTableModel) jTableList.getModel();
        modelLNhap = (DefaultTableModel) jTableLNhap.getModel();
        modelLXuat = (DefaultTableModel) jTableLXuat.getModel();
        modelLHuy = (DefaultTableModel) jTableLHuy.getModel();
        modelLTL = (DefaultTableModel) jTableLTL.getModel();
        showAllTable();
    }

    public void showTable(DefaultTableModel md) {
        int rowCount = md.getRowCount();
        // Xoá từng hàng một
        for (int i = rowCount - 1; i >= 0; i--) {
            md.removeRow(i);
        }
        listInDetails = Controller.IngredientControl.listIngredientDetails();
        for (IngredientDetails d : listInDetails) {
            md.addRow(new Object[]{
                d.getIdDetails(), d.getName(), d.getQuantity(), d.getUnit(), d.getPrice(), d.getExpire()
            });
        }
    }

    public void showAllTable() {
        showTable(modelList);
        showTable(modelNhap);
        showTable(modelXuat);
        showTable(modelHuy);
        showTable(modelTL);
    }

    public void cleartTable(DefaultTableModel md) {
        int rowCount = md.getRowCount();
        // Xoá từng hàng một
        for (int i = rowCount - 1; i >= 0; i--) {
            md.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableList = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNhap = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableLNhap = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableLXuat = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableXuat = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableLHuy = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableHuy = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableTL = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTableLTL = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NL", "Tên NL", "Số lượng", "Đơn vị", "Đơn giá", "Hạn sử dụng"
            }
        ));
        jScrollPane1.setViewportView(jTableList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1127, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kho", jPanel2);

        jTableNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NL", "Tên NL", "Số lượng còn", "Đơn vị", "Đơn giá", "Hạn sử dụng"
            }
        ));
        jTableNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNhapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableNhap);

        jTableLNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Tên NL", "Số lượng", "Đơn vị", "Đơn giá", "Hạn sử dụng"
            }
        ));
        jTableLNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableLNhapKeyPressed(evt);
            }
        });
        jScrollPane10.setViewportView(jTableLNhap);

        jButton8.setText("Lập hoá đơn");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhập NL", jPanel3);

        jTableLXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NL", "Tên NL", "Số lượng", "Đơn vị", "Hạn sử dụng"
            }
        ));
        jTableLXuat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableLXuatKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTableLXuat);

        jTableXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NL", "Tên NL", "Số lượng còn", "Đơn vị", "Đơn giá", "Hạn sử dụng"
            }
        ));
        jTableXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableXuatMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableXuat);

        jButton5.setText("Lập hoá đơn");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(23, 23, 23))))
        );

        jTabbedPane1.addTab("Xuất NL", jPanel4);

        jTableLHuy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NL", "Tên NL", "Số lượng", "Đơn vị", "Hạn sử dụng"
            }
        ));
        jTableLHuy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableLHuyKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(jTableLHuy);

        jTableHuy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NL", "Tên NL", "Số lượng còn", "Đơn vị", "Đơn giá", "Hạn sử dụng"
            }
        ));
        jTableHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHuyMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTableHuy);

        jButton6.setText("Lập hoá đơn");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addGap(23, 23, 23))))
        );

        jTabbedPane1.addTab("Huỷ NL", jPanel5);

        jTableTL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NL", "Tên NL", "Số lượng còn", "Đơn vị", "Đơn giá", "Hạn sử dụng"
            }
        ));
        jTableTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTLMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTableTL);

        jTableLTL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NL", "Tên NL", "Số lượng", "Đơn vị", "Đơn giá gốc", "Đơn giá TL"
            }
        ));
        jTableLTL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableLTLKeyPressed(evt);
            }
        });
        jScrollPane9.setViewportView(jTableLTL);

        jButton7.setText("Lập hoá đơn");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)
                        .addGap(23, 23, 23))))
        );

        jTabbedPane1.addTab("Thanh lý NL", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableXuatMouseClicked
        // TODO add your handling code here:
        boolean b = true;
        for (int i : listX) {
            if (i == jTableXuat.getSelectedRow()) {
                b = false;
                break;
            }
        }
        if (b) {
            int vitri = jTableXuat.getSelectedRow();
            listX.add(vitri);
            modelLXuat.addRow(new Object[]{
                jTableXuat.getValueAt(vitri, 0), jTableXuat.getValueAt(vitri, 1), jTableXuat.getValueAt(vitri, 2), jTableXuat.getValueAt(vitri, 3), jTableXuat.getValueAt(vitri, 5),});
        }
    }//GEN-LAST:event_jTableXuatMouseClicked

    private void jTableHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHuyMouseClicked
        // TODO add your handling code here:
        boolean b = true;
        for (int i : listH) {
            if (i == jTableHuy.getSelectedRow()) {
                b = false;
                break;
            }
        }
        if (b) {
            int vitri = jTableHuy.getSelectedRow();
            listH.add(vitri);
            modelLHuy.addRow(new Object[]{
                jTableHuy.getValueAt(vitri, 0), jTableHuy.getValueAt(vitri, 1), jTableHuy.getValueAt(vitri, 2), jTableHuy.getValueAt(vitri, 3), jTableHuy.getValueAt(vitri, 5),});
        }
    }//GEN-LAST:event_jTableHuyMouseClicked

    private void jTableTLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTLMouseClicked
        // TODO add your handling code here:
        boolean b = true;
        for (int i : listTL) {
            if (i == jTableTL.getSelectedRow()) {
                b = false;
                break;
            }
        }
        if (b) {
            int vitri = jTableTL.getSelectedRow();
            listTL.add(vitri);
            modelLTL.addRow(new Object[]{
                jTableTL.getValueAt(vitri, 0), jTableTL.getValueAt(vitri, 1), jTableTL.getValueAt(vitri, 2), jTableTL.getValueAt(vitri, 3), jTableTL.getValueAt(vitri, 4),});
        }
    }//GEN-LAST:event_jTableTLMouseClicked

    private void jTableLXuatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableLXuatKeyPressed
        // TODO add your handling code here:
        int vitri = jTableLXuat.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Double.parseDouble(modelLXuat.getValueAt(vitri, 2).toString()) == 0) {
                modelLXuat.removeRow(vitri);
            }
        }

    }//GEN-LAST:event_jTableLXuatKeyPressed

    private void jTableLHuyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableLHuyKeyPressed
        // TODO add your handling code here:
        int vitri = jTableLHuy.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Double.parseDouble(modelLHuy.getValueAt(vitri, 2).toString()) == 0) {
                modelLHuy.removeRow(vitri);
            }
        }

    }//GEN-LAST:event_jTableLHuyKeyPressed

    private void jTableLTLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableLTLKeyPressed
        // TODO add your handling code here:
        int vitri = jTableLTL.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Double.parseDouble(modelLTL.getValueAt(vitri, 2).toString()) == 0) {
                modelLTL.removeRow(vitri);
            }
        }
    }//GEN-LAST:event_jTableLTLKeyPressed

    private void jTableLNhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableLNhapKeyPressed
        // TODO add your handling code here:
        int vitri = jTableLNhap.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Double.parseDouble(modelLNhap.getValueAt(vitri, 1).toString()) == 0) {
                modelLNhap.removeRow(vitri);
            }
            if (vitri == jTableLNhap.getRowCount() - 1) {
                modelLNhap.addRow(new Object[]{});
            }
        }
    }//GEN-LAST:event_jTableLNhapKeyPressed

    private void jTableNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNhapMouseClicked
        // TODO add your handling code here:
        int vitri = jTableNhap.getSelectedRow();
        int lastRow = jTableLNhap.getRowCount() - 1;
        jTableLNhap.setValueAt(jTableNhap.getValueAt(vitri, 1), lastRow, 0);
        jTableLNhap.setValueAt(1, lastRow, 1);
        jTableLNhap.setValueAt(jTableNhap.getValueAt(vitri, 3), lastRow, 2);
        jTableLNhap.setValueAt(jTableNhap.getValueAt(vitri, 4), lastRow, 3);
        modelLNhap.addRow(new Object[]{});
    }//GEN-LAST:event_jTableNhapMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Bạn có muốn lập hoá đơn?") == 0) {
            int rowCount = jTableLNhap.getRowCount();
            ArrayList<IngredientDetails> LNhap = new ArrayList<>();
            for (int i = 0; i < rowCount - 1; i++) {
                boolean b = true;
                String name = jTableLNhap.getValueAt(i, 0).toString();
                double quantity = Double.parseDouble(jTableLNhap.getValueAt(i, 1).toString());
                int price = Integer.parseInt(jTableLNhap.getValueAt(i, 3).toString());
                LocalDate expire = null;
                if (jTableLNhap.getValueAt(i, 4) != null) {
                    expire = LocalDate.parse(jTableLNhap.getValueAt(i, 4).toString());
                }
                IngredientDetails inDetails = null;
                for (Ingredient in : listIngredient) {
                    if (name.equals(in.getName())) {         //In cũ
                        String idInDetails = Controller.IngredientControl.ReturnNextIDIngredientDetails(in.getId());
                        inDetails = new IngredientDetails(in.getId(), in.getName(), in.getUnit(), idInDetails, quantity, price, expire);
                        Controller.IngredientControl.addIngredientDetails(inDetails);
                        b = false;
                        break;
                    }
                }
                if (b) {
                    String idIngredient = Controller.IngredientControl.ReturnNextIDIngredient();
                    String idInDetails = Controller.IngredientControl.ReturnNextIDIngredientDetails(idIngredient);
                    inDetails = new IngredientDetails(idIngredient, jTableLNhap.getValueAt(i, 0).toString(), jTableLNhap.getValueAt(i, 2).toString(), idInDetails, quantity, price, expire);
                    Controller.IngredientControl.addIngredientDetails(inDetails);
                }
                LNhap.add(inDetails);
            }
            Controller.InvoiceControl.addInvoiceNhap(LNhap, e.getId());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Bạn có muốn lập hoá đơn?") == 0) {
            int rowCount = jTableLXuat.getRowCount();
            ArrayList<IngredientDetails> LXuat = new ArrayList<>();
            boolean b = true;
            for (int i = 0; i < rowCount; i++) {
                String id = jTableLXuat.getValueAt(i, 0).toString();
                double quantity = Double.parseDouble(jTableLXuat.getValueAt(i, 2).toString());
                if (quantity > Controller.IngredientControl.getQuantity(id)) {
                    JOptionPane.showMessageDialog(null, "Số lượng xuất nhiều hơn số lượng hiện có!!");
                    b = false;
                    break;
                } else {
                    LXuat.add(new IngredientDetails(id, quantity));
                }
            }
            if (b) {
                Controller.InvoiceControl.addInvoiceXuat(LXuat, e.getId());
                showAllTable();
                cleartTable(modelLXuat);
                listX.clear();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Bạn có muốn lập hoá đơn?") == 0) {
            int rowCount = jTableLHuy.getRowCount();
            ArrayList<IngredientDetails> LHuy = new ArrayList<>();
            boolean b = true;
            for (int i = 0; i < rowCount; i++) {
                String id = jTableLHuy.getValueAt(i, 0).toString();
                double quantity = Double.parseDouble(jTableLHuy.getValueAt(i, 2).toString());
                if (quantity > Controller.IngredientControl.getQuantity(id)) {
                    JOptionPane.showMessageDialog(null, "Số lượng huỷ nhiều hơn số lượng hiện có!!");
                    b = false;
                    break;
                } else {
                    LHuy.add(new IngredientDetails(id, quantity));
                }
            }
            if (b) {
                Controller.InvoiceControl.addInvoiceHuy(LHuy, e.getId());
                showAllTable();
                cleartTable(modelLHuy);
                listH.clear();
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Bạn có muốn lập hoá đơn?") == 0) {
            int rowCount = jTableLTL.getRowCount();
            ArrayList<IngredientDetails> LTL = new ArrayList<>();
            boolean b = true;
            for (int i = 0; i < rowCount; i++) {
                String id = jTableLTL.getValueAt(i, 0).toString();
                double quantity = Double.parseDouble(jTableLTL.getValueAt(i, 2).toString());
                int price = Integer.parseInt(jTableLTL.getValueAt(i, 5).toString());
                if (quantity > Controller.IngredientControl.getQuantity(id)) {
                    JOptionPane.showMessageDialog(null, "Số lượng thanh lý nhiều hơn số lượng hiện có!!");
                    b = false;
                    break;
                } else {
                    LTL.add(new IngredientDetails(id, quantity, price));
                }
            }
            if (b) {
                Controller.InvoiceControl.addInvoiceTL(LTL, e.getId());
                showAllTable();
                cleartTable(modelLTL);
                listTL.clear();
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StorageManegement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StorageManegement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StorageManegement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StorageManegement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StorageManegement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableHuy;
    private javax.swing.JTable jTableLHuy;
    private javax.swing.JTable jTableLNhap;
    private javax.swing.JTable jTableLTL;
    private javax.swing.JTable jTableLXuat;
    private javax.swing.JTable jTableList;
    private javax.swing.JTable jTableNhap;
    private javax.swing.JTable jTableTL;
    private javax.swing.JTable jTableXuat;
    // End of variables declaration//GEN-END:variables
}
